GET http://localhost:7769/api/users


###

POST http://localhost:7769/api/users
Content-Type: application/json

{
    "title": "Mr",
    "userName": "octane2",
    "firstName": "Perry",
    "lastName": "Nebular",
    "address": "100 Address st",
    "countryCode": 234,
    "phoneNumber": 8035549659,
    "email": "octane2@example.com",
    "bank_name": "Best Bank Bank Name",
    "bank_account_number": 887603035566277,
    "bvn": 7383836767939393900,
    "system_account_number": 4066327444452320774,
    "password": "password"
    }

###
POST http://localhost:7769/api/users/login/magic
Content-Type: application/json

{
    "firstName": "magic",
    "password": "passpass"
}

###

    
POST http://localhost:7769/api/users/login
Content-Type: application/json

{
    "firstName": "Jes",
    "lastName": "Ter",
    "password": "password2"
}


###

    
POST http://localhost:7769/api/users/login/username/primefirst
Content-Type: application/json

{
    "username": "primefirst",
    "password": "1111"
}

###
POST http://localhost:7769/api/users/login/phonenumber/8034945217
Content-Type: application/json

{
    "phoneNumber": "8034945217",
    "password": "passpass"
}


# ###
# POST http://localhost:7760/api/users/user/email/magicone@example.com
# Content-Type: application/json

# {
#     "email": "magicone@example.com",
#     "password": passpass
# }