GET http://localhost:7769/api/users


###

POST http://localhost:7769/api/users
Content-Type: application/json

{
    "title": "Mr",
    "userName": "octane",
    "firstName": "Perry",
    "lastName": "Nebula",
    "address": "10 Address st",
    "countryCode": 234,
    "phoneNumber": 8045549659,
    "email": "octane@example.com",
    "bank_name": "Best Bank Bank Name",
    "bank_account_number": 887600885566277,
    "bvn": 738383939939393900,
    "system_account_number": 40207444452320774,
    "accountBalance": 70000000000.56,
    "password": "password"
    }

###
POST http://localhost:7769/api/users/login/magic
Content-Type: application/json

{
    "firstName": "magic",
    "password": "passpass"
}

###

    
POST http://localhost:7769/api/users/login
Content-Type: application/json

{
    "firstName": "Jes",
    "lastName": "Ter",
    "password": "password2"
}


###
POST http://localhost:7760/api/users/login/magicone@example.com
Content-Type: application/json

{
    "email": "magicone@example.com",
    "password": passpass
}


###
POST http://localhost:7760/api/users/user/email/magicone@example.com
Content-Type: application/json

{
    "email": "magicone@example.com",
    "password": passpass
}